### ISSUE TITLE
[Feature] Preview files not in an open Folder or Workspace 

### ISSUE THREAD

**Issue by nanangp** [nanangp/vscode-wireviz-preview#1]
Waiting for stdout support (wireviz/WireViz#320) to be released (potentially when they get to 0.4.0?)

**Comment by martinrieder** [comment]
Please note that wireviz/WireViz#321 resolves wireviz/WireViz#320, which is now part of the 0.4 release. It may not be necessary to reopen this issue due to #5.

**Comment by nanangp** [comment]
> wireviz/WireViz#321 ... which is now part of the 0.4 release

Doesn't look like it has been merged. Had a look the 0.4 commit and couldn't find any of the changes. 

Also, this bug turned out to not need stdin/out after all, and was resolved another way.
