### ISSUE TITLE
[Bug] Cannot preview harnesses with images

### ISSUE THREAD

**Issue by robotskirts** [nanangp/vscode-wireviz-preview#3]
Most of my harnesses have images in them implemented exactly as they are in example 08 https://github.com/wireviz/WireViz/blob/master/examples/readme.md#example-08

The Wireviz Preview throws an error that it's looking for the image file in a path relative to the output directory instead of relative to the input yml. e.g. output/resources/stereo-phone-plug-TRS.png instead of the correct resources/stereo-phone-plug-TRS.png

I tested demo02.yml on this MacOS install of VS Code and it worked fine when their weren't images.

**Comment by nanangp** [comment]
Oh thanks. In hindsight, I probably should have run it against the full wireviz example suite.

This, unfortunately, seems to be a wireviz limitation. We get the error just running `wireviz "ex08.yml" -o "output/ex08"`  
I'll change the extension back to not outputting to a subdirectory for now - which means cluttering the input dir, but better than not working i guess?

**Comment by robotskirts** [comment]
It might be fixed in the dev branch already which I've never used. https://github.com/wireviz/WireViz/issues/284

I just use a tasks.json task to run wireviz now so I was already cluttering the input directory... probably because of this exact bug, I just don't remember :)

**Comment by nanangp** [comment]
Yeah, actually I remember seeing that when going through their closed issues some time ago. It's unfortunate that `dev` has been around for more than 2, years and doesn't seem any closer to making it to release. It has a number of good stuff that we could really use here.

**Comment by nanangp** [comment]
Hmmh, this is more annoying than it should be. Just found out the WebView in VSCode won't show external images inside an SVG (also tested on every other SVG Viewer extensions in the marketplace).  I'll put in some workarounds in config, for people that want to use images.

**Comment by nanangp** [comment]
Closing this for now. See the **Limitations** section in [README.md](README.md). 

We'll revisit when/if the `dev` branch of WireViz makes it into stable.
