### ISSUE TITLE
WebView ignores panel layout and always opens to the side

### ISSUE THREAD

**Issue by martinrieder** [nanangp/vscode-wireviz-preview#4]
I prefer to use the editor layout vertically instead of horizontally. The WireViz diagrams that I generate tend to have a landscape orientation. Currently, the layout changes every time the preview is regenerated. 

As a simple fix, I propose to exchange `wvpanelColumn` for `docColumn.Beside`. It works nicely in my use case, but please confirm whether this is okay in general.

**Comment by martinrieder** [comment]
Just pasting the code for easy reference:
`// If we have to dispose an existing one, we'd like to recreate at the same location`
`//const wvpanelColumn = wvpanel?.viewColumn;`
`const docColumn = vscode_2.window.activeTextEditor?.viewColumn;`
`const wvpanelColumn = docColumn.Beside; // get the column beside the editor`

**Comment by nanangp** [comment]
The API says `viewColumn`, you're not supposed to arrange them in rows! 🙃

**Comment by martinrieder** [comment]
Nice. Thanks for the quick resolution. It works as expected now. 👍
