### ISSUE TITLE
Detect appropriate WireViz version

### ISSUE THREAD

**Issue by nanangp** [nanangp/vscode-wireviz-preview#6]
With #5 breaking backwards compatibility with WV 0.3, it would be nice for the upcoming version that supports 0.4 onwards to inform users if they're running an older version.

**Comment by martinrieder** [comment]
@nanangp I am considering to create a schema definition for the WireViz syntax. This would allow the language server to do some live checks while editing.

From https://github.com/redhat-developer/yaml-language-server :
> Associating a schema in the YAML file
It is possible to specify a yaml schema using a modeline. Schema url can be a relative path. If a relative path is specified, it is calculated from yaml file path, not from workspace root path

`# yaml-language-server: $schema=<urlToTheSchema>`

I created wireviz/WireViz#348 to have a compatibility check, but realized that schema validation might be what is truly needed.
